<?php
$url = 'https://www.caipiaokong.com/lottery/hgklb.html';
$info=file_get_contents($url);
preg_match_all ("|</span></td><td>(.*?)</span></td></tr><tr class='alt'><td><span class='xs0'>|i", $info, $ml);
preg_match_all ("|</strong></td><td>(.*?)</span></td></tr><tr class='alt'><td><span class='xs0'>|i", $info, $time);
preg_match_all ("|</th></tr><tr><td><span class='xs0'>(.*?)</span></td><td>|i", $info, $qs);
$a=$ml[0][0];
$a=str_replace('</strong>',',',$a);
$a= strip_tags($a);
$a= substr($a,0,strlen($a)-6);
$qs=$qs[0][0];
$qs=preg_match_all('/\d+/',$qs,$arr);
$arr = join('',$arr[0]);
$arr= substr($arr,1);
$sj=$time[0][0];
$sj= strip_tags($sj);
$b= substr($a,0,strlen($a)-57);
$b1= substr($a,3,strlen($a)-57);
$b2= substr($a,6,strlen($a)-57);
$b3= substr($a,9,strlen($a)-57);
$c= substr($a,12,strlen($a)-57);
$c1= substr($a,15,strlen($a)-57);
$c2= substr($a,18,strlen($a)-57);
$c3= substr($a,21,strlen($a)-57);
$d= substr($a,24,strlen($a)-57);
$d1= substr($a,27,strlen($a)-57);
$d2= substr($a,30,strlen($a)-57);
$d3= substr($a,33,strlen($a)-57);
$f= substr($a,36,strlen($a)-57);
$f1= substr($a,39,strlen($a)-57);
$f2= substr($a,42,strlen($a)-57);
$f3= substr($a,45,strlen($a)-57);
$e= substr($a,48,strlen($a)-57);
$e1= substr($a,51,strlen($a)-57);
$e2= substr($a,54,strlen($a)-57);
$e3= substr($a,57,strlen($a)-57);
$b=$b+$b1+$b2+$b3;
$c=$c+$c1+$c2+$c3;
$d=$d+$d1+$d2+$d3;
$f=$f+$f1+$f2+$f3;
$e=$e+$e1+$e2+$e3;
$nub1= substr($b,-1);
$nub2= substr($c,-1);
$nub3= substr($d,-1);
$nub4= substr($f,-1);
$nub5= substr($e,-1);
$nub= $nub1.','.$nub2.','.$nub3.','.$nub4.','.$nub5;
header("Content-type: application/xml");
echo'<?xml version="1.0" encoding="utf-8"?>';
echo '<xml><row expect="'.$arr.'" opencode="'.$nub.'" opentime="'.date('Y-m-d ').$sj.'"/></xml>';
ob_end_flush();
?>
